import "../package.json";
import SessionProvider from "@/components/SessionProvider";
import "./globals.css";
import { getServerSession } from "next-auth";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Providers>
          <main>
            <div className="container mx-auto max-w-full min-h-screen">
              <Navbar />
              {children}
              <Footer />
            </div>
          </main>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}

