import { Metadata } from "next";
import "@/app/global.css";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
      <EdgeStoreProvider>
        <main>
          <div className="container mx-auto max-w-full min-h-screen">
           {children}
          </div>
        </main>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
